const {
    VITE_API_COUNTRIES,
    VITE_API_OPEN_WEATHER,
    VITE_API_KEY_OPEN_WEATHER,
    VITE_API_ICON_OPEN_WEATHER,
} = import.meta.env;
  
const API_COUNTRIES = VITE_API_COUNTRIES;
const API_WEATHER = VITE_API_OPEN_WEATHER;
const KEY_WEATHER = VITE_API_KEY_OPEN_WEATHER;
const IMG_WEATHER = VITE_API_ICON_OPEN_WEATHER;

export default {
    API_COUNTRIES,
    API_WEATHER,
    KEY_WEATHER,
    IMG_WEATHER
}